version: '3.8'

services:
  redis_db:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    container_name: redis_db
    command: redis-server
    volumes:
      - ./redis-data:/var/lib/data/redis

  db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432
    volumes:
      - ./postgres-data:/var/lib/data/postgres

  blockscout:
    depends_on:
      - db
      - redis_db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        DISABLE_READ_API: "false"
        API_PATH: "/"
        NETWORK_PATH: "/"
        DISABLE_WEBAPP: "false"
        DISABLE_WRITE_API: "true"
        CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        SOCKET_ROOT: "/"
        WOBSERVER_ENABLED: "false"
        ADMIN_PANEL_ENABLED: ""
    restart: always
    container_name: 'blockscout'
    environment:
        DISABLE_WEBAPP: "false"
        DISABLE_READ_API: "false"
        DISABLE_WRITE_API: "true"
        DISABLE_INDEXER: "true"
        DISABLE_REALTIME_INDEXER: "false"
        INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "false"
        INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: "true"
        INDEXER_CATCHUP_BLOCKS_BATCH_SIZE: "50"
        INDEXER_CATCHUP_BLOCKS_CONCURRENCY: "50"

    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    ports:
      - 4000:4000

volumes:
  redis-data:
    external: true
  postgres-data:
    external: true